/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://2l6c3ykh7rgijcjys5lnsrocpu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-n4nfksdppfabjj6hthyfp6fdni",
    "aws_cognito_identity_pool_id": "us-west-2:25f75500-0593-4d8c-bcff-79e211a574a0",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_liaoEXSxF",
    "aws_user_pools_web_client_id": "42uc4s7cnmkf9ji4vuknj4c6al",
    "oauth": {},
    "aws_user_files_s3_bucket": "postagrama65c4e11566f4f7ba11b7c868d715952143426-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
